Repository redux-orm/redux-orm, pull requests merged in 2019-10, with the labels that each got.

#311 fix: handle 'desc' order in QuerySet.orderBy
  src/QuerySet.js
  src/db/Table.js
  src/test/unit/Table.js
Labels: layer: Database, type: Bug

#315 Fix fieldModel not being passed to all field selectors
  src/selectors/index.js
  src/test/integration/selectors.js
Labels: layer: Fields, type: Bug

#318 Allow mapping map selectors
  src/redux.js
  src/selectors/FieldSelectorSpec.js
  src/selectors/MapSelectorSpec.js
  src/test/integration/selectors.js
Labels: layer: Selectors, status: Please Review, type: Bug
